quarkus.http.port=8087
quarkus.application.name=ms-reportes

# --- Cliente REST hacia MS-KPIs ---
quarkus.rest-client.kpis-api.url=http://localhost:8086
quarkus.rest-client.kpis-api.scope=jakarta.enterprise.context.ApplicationScoped
quarkus.rest-client.kpis-api.connect-timeout=5000
quarkus.rest-client.kpis-api.read-timeout=5000

# --- Cliente REST hacia MS-Datos (nombres de sucursal para reportes) ---
quarkus.rest-client.datos-api.url=http://localhost:8089
quarkus.rest-client.datos-api.scope=jakarta.enterprise.context.ApplicationScoped
quarkus.rest-client.datos-api.connect-timeout=5000
quarkus.rest-client.datos-api.read-timeout=5000

# --- Configuracion de pruebas ---
%test.quarkus.rest-client.kpis-api.url=http://localhost:8086
%test.quarkus.rest-client.datos-api.url=http://localhost:8089
