quarkus.http.port=8087
quarkus.application.name=ms-reportes

# --- Cliente REST hacia MS-KPIs ---
quarkus.rest-client.kpis-api.url=http://localhost:8086
quarkus.rest-client.kpis-api.scope=jakarta.enterprise.context.ApplicationScoped
quarkus.rest-client.kpis-api.connect-timeout=5000
quarkus.rest-client.kpis-api.read-timeout=5000

# --- Configuracion de pruebas ---
%test.quarkus.rest-client.kpis-api.url=http://localhost:8086
