# Puerto del BFF
quarkus.http.port=${PORT:8081}

# REST Client para ms-datos
ms-datos/mp-rest/url=${MS_DATOS_URL:http://localhost:8080}
ms-datos/mp-rest/scope=jakarta.inject.Singleton

# Swagger
quarkus.swagger-ui.always-include=true

# Jackson
quarkus.jackson.serialization.write-dates-as-timestamps=false
