# Puerto del BFF
quarkus.http.port=${PORT:8090}

# REST Clients — URLs de los microservicios
ms-datos/mp-rest/url=${MS_DATOS_URL:http://localhost:8082}
ms-datos/mp-rest/scope=jakarta.inject.Singleton

ms-auth/mp-rest/url=${MS_AUTH_URL:http://localhost:8080}
ms-auth/mp-rest/scope=jakarta.inject.Singleton

ms-users/mp-rest/url=${MS_USERS_URL:http://localhost:8081}
ms-users/mp-rest/scope=jakarta.inject.Singleton

ms-kpis/mp-rest/url=${MS_KPIS_URL:http://localhost:8086}
ms-kpis/mp-rest/scope=jakarta.inject.Singleton

ms-reportes/mp-rest/url=${MS_REPORTES_URL:http://localhost:8087}
ms-reportes/mp-rest/scope=jakarta.inject.Singleton

# Swagger
quarkus.swagger-ui.always-include=true

# Jackson
quarkus.jackson.serialization.write-dates-as-timestamps=false
