quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usuario_cordillera
quarkus.datasource.password=cordillera_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/db_users
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.swagger-ui.always-include=true

quarkus.management.auth.enabled=false
quarkus.swagger-ui.path=/swagger-ui

# CORS — permite llamadas desde el frontend en desarrollo
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true
