quarkus.http.port=8085

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=usuario_cordillera
quarkus.datasource.password=cordillera_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/db_users
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.swagger-ui.always-include=true

quarkus.management.auth.enabled=false
quarkus.swagger-ui.path=/swagger-ui
